export const cards = [
  {
    id: 1,
    title: 'Shoes',
    image: 'shoes',
    rating: 5,
    basePrice: '500$',
    discount: '10%',
    stock: 13,
    brand: 'Puma',
    category: 'Footwear',
    description: 'Comfortable running shoes',
  },
  {
    id: 2,
    title: 'T-Shirt',
    image: 'tshirt',
    rating: 4,
    basePrice: '20$',
    discount: '5%',
    stock: 21,
    brand: 'Nike',
    category: 'Apparel',
    description: 'Lightweight breathable t-shirt',
  },
  {
    id: 3,
    title: 'Backpack',
    image: 'backpack',
    rating: 4.5,
    basePrice: '70$',
    discount: '15%',
    stock: 10,
    brand: 'Adidas',
    category: 'Accessories',
    description: 'Durable travel backpack',
  },
  {
    id: 4,
    title: 'Smartwatch',
    image: 'smartwatch',
    rating: 5,
    basePrice: '250$',
    discount: '20%',
    stock: 5,
    brand: 'Apple',
    category: 'Electronics',
    description: 'Latest generation smartwatch',
  },
  {
    id: 5,
    title: 'Sunglasses',
    image: 'sunglasses',
    rating: 4,
    basePrice: '150$',
    discount: '25%',
    stock: 15,
    brand: 'Ray-Ban',
    category: 'Accessories',
    description: 'Stylish protection from the sun',
  },
  {
    id: 6,
    title: 'Laptop',
    image: 'laptop',
    rating: 4.5,
    basePrice: '1200$',
    discount: '10%',
    stock: 8,
    brand: 'Dell',
    category: 'Electronics',
    description: 'High performance for gaming and work',
  },
  {
    id: 7,
    title: 'Coffee Mug',
    image: 'coffee_mug',
    rating: 4.5,
    basePrice: '15$',
    discount: '5%',
    stock: 25,
    brand: 'Generic',
    category: 'Home goods',
    description: 'Keep your drink warm or cold for hours',
  },
  {
    id: 8,
    title: 'Water Bottle',
    image: 'water_bottle',
    rating: 4,
    basePrice: '30$',
    discount: '10%',
    stock: 20,
    brand: 'Hydro Flask',
    category: 'Accessories',
    description: 'Stainless steel, vacuum insulated water bottle',
  },
  {
    id: 9,
    title: 'Headphones',
    image: 'headphones',
    rating: 5,
    basePrice: '100$',
    discount: '20%',
    stock: 12,
    brand: 'Sony',
    category: 'Electronics',
    description: 'Noise cancelling over-ear headphones',
  },
];
